### ISSUE TITLE
More config options / a better config system.

### ISSUE THREAD

**Issue by ddm999** [danieljabailey/two-bot#1]
To allow for different:
- [ ] Bridging bots (no hardcoded bot ID)
- [ ] Messages for:
  - [ ] Being "%s'd"
  - [ ] Viewing leaderboard
  - [ ] Viewing individual scores
- [ ] Number of people visible on the main leaderboard
- [ ] Rate limit
- [ ] Data filename

**Comment by danieljabailey** [comment]
Closing as unnecessary. Reopen when two bot is widely used in the wild. :P
