### ISSUE TITLE
channels.info deprecated, will be removed

### ISSUE THREAD

**Issue by sersorrel** [danieljabailey/two-bot#7]
two-bot will break on 2021-02-24: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api

the issue is here:

https://github.com/danieljabailey/two-bot/blob/fb11f3304de757c5b7a0862a7860acb5810cff3d/two.py#L101-L105

it _might_ be possible to literally just replace the call to `channels_info` with an identical call to `conversations_info`.

**Comment by danieljabailey** [comment]
Ah, that's annoying.
Has someone else nominated themselves to maintain two-bot for hacksoc's purposes?
Since I've left I'm probably not gonna touch this code base again.
I hope someone forks two-bot to keep it going (if it's still wanted).

**Comment by sersorrel** [comment]
a couple of people have started complete rewrites, afaik :upside_down_face: so maybe they'll go somewhere, or maybe someone'll patch two-bot, idk

**Comment by danieljabailey** [comment]
Cool, I'll leave it to one of them to sort this out then, closing this issue for now.
